<template>
  <div class="notification-container">
    <!-- 顶部工具栏 -->
    <div class="toolbar">
      <div class="toolbar-left">
        <h1 class="title">
          <i class="fa fa-bell fa-lg"></i>
          通知中心
          <span v-if="unreadCount > 0" class="badge">{{ unreadCount }}</span>
        </h1>
      </div>      <div class="toolbar-right">
        <!-- 操作按钮 -->
        <div class="action-buttons">
          <button @click="markAllAsRead" class="action-btn" :disabled="unreadCount === 0">
            <i class="fa fa-check-double"></i>
            全部已读
          </button>
          <button @click="refreshNotifications" class="action-btn" :disabled="loading">
            <i class="fa fa-refresh" :class="{ 'fa-spin': loading }"></i>
            刷新
          </button>
          <button @click="showSettingsModal = true" class="action-btn">
            <i class="fa fa-cog"></i>
            设置
          </button>
        </div>
      </div>
    </div>
      <!-- 通知区域 -->
    <div class="section">
      <!-- 错误提示 -->
      <div v-if="error" class="error-message">
        <i class="fa fa-exclamation-triangle"></i>
        {{ error }}
        <button @click="error = null" class="close-error">
          <i class="fa fa-times"></i>
        </button>
      </div>
      
      <!-- 批量操作工具栏 -->
      <div v-if="showBatchActions" class="batch-actions-toolbar">
        <div class="batch-info">
          <span>已选择 {{ selectedNotifications.length }} 条通知</span>
          <button @click="selectedNotifications = []" class="clear-selection">
            <i class="fa fa-times"></i>
            取消选择
          </button>
        </div>
        <div class="batch-buttons">
          <button @click="markSelectedAsRead" class="batch-btn">
            <i class="fa fa-check"></i>
            标记已读
          </button>
          <button @click="deleteSelectedNotifications" class="batch-btn delete">
            <i class="fa fa-trash"></i>
            批量删除
          </button>
        </div>
      </div>

      <!-- 选择工具栏 -->
      <div v-if="filteredNotifications.length > 0" class="selection-toolbar">
        <div class="selection-controls">
          <button @click="toggleSelectAll" class="select-all-btn">
            <i class="fa fa-check-square" v-if="selectedNotifications.length === filteredNotifications.length"></i>
            <i class="fa fa-square-o" v-else></i>
            {{ selectedNotifications.length === filteredNotifications.length ? '取消全选' : '全选' }}
          </button>
        </div>
      </div>

      <!-- 筛选器 -->
      <div class="filter-tabs">
        <button 
          v-for="filter in filters" 
          :key="filter.key"
          @click="activeFilter = filter.key"
          :class="['filter-tab', { active: activeFilter === filter.key }]"
        >
          <i :class="filter.icon"></i>
          {{ filter.label }}
          <span v-if="getFilterCount(filter.key) > 0" class="filter-count">{{ getFilterCount(filter.key) }}</span>
        </button>
      </div>

      <!-- 加载状态 -->
      <div v-if="loading" class="loading-state">
        <i class="fa fa-spinner fa-spin fa-2x"></i>
        <p>正在加载通知...</p>
      </div>     
       <!-- 通知列表 -->
      <div v-else-if="filteredNotifications.length" class="notification-list">
        <div 
          v-for="notification in filteredNotifications" 
          :key="notification.id" 
          :class="['notification-card', notification.priority, { 
            unread: !notification.read,
            'auto-generated': notification.autoGenerated,
            'selected': selectedNotifications.includes(notification.id)
          }]"
        >
          <div class="notification-checkbox">
            <input 
              type="checkbox" 
              :id="`notification-${notification.id}`"
              :checked="selectedNotifications.includes(notification.id)"
              @change="toggleNotificationSelection(notification.id)"
            />
            <label :for="`notification-${notification.id}`" class="checkbox-label"></label>
          </div>
          
          <div class="notification-content-wrapper"
               @click="!selectedNotifications.includes(notification.id) && !notification.read && markAsRead(notification.id)">
            <div class="notification-header">
              <div class="notification-meta">
                <span class="notification-type">
                  <i :class="getTypeIcon(notification.type)"></i>
                  {{ getTypeLabel(notification.type) }}
                  <span v-if="notification.autoGenerated" class="auto-tag">自动</span>
                </span>
                <span v-if="notification.courseName" class="course-name">{{ notification.courseName }}</span>
                <span v-if="notification.senderRole" class="sender-role">
                  {{ getSenderRoleLabel(notification.senderRole) }}
                </span>
              </div>
              <div class="notification-actions">
                <button v-if="!notification.read" @click.stop="markAsRead(notification.id)" class="mark-read-btn">
                  <i class="fa fa-check"></i>
                </button>
                <button @click.stop="deleteNotification(notification.id)" class="delete-btn">
                  <i class="fa fa-trash"></i>
                </button>
              </div>
            </div>
            
            <h2 class="notification-title">{{ notification.title }}</h2>
            <p class="notification-content">{{ notification.content }}</p>
            
            <!-- 标签 -->
            <div v-if="notification.tags && notification.tags.length" class="notification-tags">
              <span v-for="tag in notification.tags" :key="tag" class="tag">{{ tag }}</span>
            </div>
            
            <div class="notification-footer">
              <span class="notification-date">
                <i class="fa fa-clock-o"></i>
                {{ formatDate(notification.createdAt) }}
              </span>
              <span v-if="notification.dueDate" class="due-date" :class="getDueDateClass(notification.dueDate)">
                <i class="fa fa-calendar"></i>
                截止: {{ formatDate(notification.dueDate) }}
              </span>
              <a v-if="notification.link" :href="notification.link" class="task-link" target="_blank" @click.stop>
                <i class="fa fa-external-link"></i>
                查看任务
              </a>
            </div>
          </div>
        </div>
      </div>
      <div v-else class="no-notifications">
        <i class="fa fa-inbox fa-3x"></i>
        <p>{{ getEmptyMessage() }}</p>
      </div>
    </div>

    <!-- 个人任务清单 -->
    <div class="section">
      <div class="section-header">
        <h2 class="section-title">
          <i class="fa fa-list-check fa-lg"></i>
          我的任务清单
          <span v-if="incompleteTasks > 0" class="task-badge">{{ incompleteTasks }}</span>
        </h2>
        <div class="task-filter">
          <button 
            @click="showCompletedTasks = !showCompletedTasks"
            :class="['filter-toggle', { active: showCompletedTasks }]"
          >
            <i class="fa fa-eye" v-if="!showCompletedTasks"></i>
            <i class="fa fa-eye-slash" v-else></i>
            {{ showCompletedTasks ? '隐藏已完成' : '显示已完成' }}
          </button>
        </div>
      </div>
      
      <div class="task-input">
        <input 
          v-model="newTaskTitle" 
          @keyup.enter="addPersonalTask"
          placeholder="添加个人任务..."
          class="task-input-field"
        />
        <input 
          v-model="newTaskDueDate"
          type="datetime-local"
          class="task-date-input"
          placeholder="截止日期（可选）"
        />
        <select v-model="newTaskPriority" class="task-priority-select">
          <option value="low">低优先级</option>
          <option value="medium">中优先级</option>
          <option value="high">高优先级</option>
        </select>
        <button @click="addPersonalTask" class="add-task-btn" :disabled="!newTaskTitle.trim()">
          <i class="fa fa-plus"></i>
          添加
        </button>
      </div>

      <div v-if="filteredPersonalTasks.length" class="personal-task-list">
        <div 
          v-for="task in filteredPersonalTasks" 
          :key="task.id" 
          :class="['personal-task-item', task.priority, { 
            completed: task.completed,
            overdue: isTaskOverdue(task) 
          }]"
        >
          <div class="task-checkbox">
            <input 
              type="checkbox" 
              :id="`task-${task.id}`"
              v-model="task.completed"
              @change="updatePersonalTask(task)"
            />
            <label :for="`task-${task.id}`" class="checkbox-label"></label>
          </div>
          <div class="task-content">
            <span class="task-title">{{ task.title }}</span>
            <span v-if="task.description" class="task-description">{{ task.description }}</span>
            <div class="task-meta">
              <span class="task-date">{{ formatDate(task.createdAt) }}</span>
              <span v-if="task.dueDate" class="task-due-date" :class="{ overdue: isTaskOverdue(task) }">
                <i class="fa fa-calendar"></i>
                {{ formatDate(task.dueDate) }}
              </span>
              <span class="task-priority-indicator" :class="task.priority">
                {{ getPriorityLabel(task.priority) }}
              </span>
            </div>
          </div>
          <div class="task-actions">
            <button @click="editPersonalTask(task)" class="edit-task-btn">
              <i class="fa fa-edit"></i>
            </button>
            <button @click="deletePersonalTask(task.id)" class="delete-task-btn">
              <i class="fa fa-trash"></i>
            </button>
          </div>
        </div>
      </div>
      <div v-else class="no-tasks">
        <i class="fa fa-tasks fa-2x"></i>
        <p>{{ showCompletedTasks ? '没有已完成的任务' : '还没有个人任务，添加一个开始吧！' }}</p>
      </div>
    </div>    <!-- 编辑任务模态框 -->
    <Teleport to="body">
      <div v-if="showEditTaskModal" class="modal-overlay" @click.self="closeEditTaskModal">
        <div class="modal-content">
          <div class="modal-header">
            <h3>编辑任务</h3>
            <button @click="closeEditTaskModal" class="modal-close">
              <i class="fa fa-times"></i>
            </button>
          </div>
          <div class="modal-body">
            <form @submit.prevent="saveEditedTask">
              <div class="form-group">
                <label>任务标题:</label>
                <input v-model="editingTask.title" type="text" required />
              </div>
              <div class="form-group">
                <label>任务描述:</label>
                <textarea v-model="editingTask.description" rows="3"></textarea>
              </div>
              <div class="form-group">
                <label>截止日期:</label>
                <input v-model="editingTask.dueDate" type="datetime-local" />
              </div>
              <div class="form-group">
                <label>优先级:</label>
                <select v-model="editingTask.priority">
                  <option value="low">低优先级</option>
                  <option value="medium">中优先级</option>
                  <option value="high">高优先级</option>
                </select>
              </div>
              <div class="form-actions">
                <button type="button" @click="closeEditTaskModal" class="cancel-btn">取消</button>
                <button type="submit" class="submit-btn">保存修改</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </Teleport>

    <!-- 通知设置 -->
    <Teleport to="body">
      <div v-if="showSettingsModal" class="modal-overlay" @click.self="closeSettingsModal">
        <div class="modal-content">
          <div class="modal-header">
            <h3>通知设置</h3>
            <button @click="closeSettingsModal" class="modal-close">
              <i class="fa fa-times"></i>
            </button>
          </div>
          <div class="modal-body">
            <form @submit.prevent="saveNotificationSettings">
              <div class="form-group">
                <label>启用推送通知:</label>
                <input 
                  type="checkbox" 
                  v-model="notificationSettings.enablePush" 
                  class="toggle-checkbox"
                />
                <span class="toggle-label">{{ notificationSettings.enablePush ? '已启用' : '已禁用' }}</span>
              </div>
              <div class="form-group">
                <label>启用邮件通知:</label>
                <input 
                  type="checkbox" 
                  v-model="notificationSettings.enableEmail" 
                  class="toggle-checkbox"
                />
                <span class="toggle-label">{{ notificationSettings.enableEmail ? '已启用' : '已禁用' }}</span>
              </div>
              <div class="form-group">
                <label>截止日期提醒:</label>
                <input 
                  type="checkbox" 
                  v-model="notificationSettings.enableDeadlineReminders" 
                  class="toggle-checkbox"
                />
                <span class="toggle-label">{{ notificationSettings.enableDeadlineReminders ? '已启用' : '已禁用' }}</span>
              </div>
              <div class="form-group" v-if="notificationSettings.enableDeadlineReminders">
                <label>提醒时间:</label>                
                <div class="reminder-times">
                  <div v-for="(_, index) in notificationSettings.reminderDays" :key="index" class="reminder-time">
                    <input 
                      type="number" 
                      v-model="notificationSettings.reminderDays[index]"
                      min="0"
                      class="reminder-input"
                    />
                    <span class="reminder-unit">天</span>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label>静音时段:</label>
                <input 
                  type="checkbox" 
                  v-model="notificationSettings.quietHours.enabled" 
                  class="toggle-checkbox"
                />
                <span class="toggle-label">{{ notificationSettings.quietHours.enabled ? '已启用' : '已禁用' }}</span>
                <div v-if="notificationSettings.quietHours.enabled" class="quiet-hours-settings">
                  <div class="quiet-hour">
                    <label>开始时间:</label>
                    <input 
                      type="time" 
                      v-model="notificationSettings.quietHours.start" 
                      class="time-input"
                    />
                  </div>
                  <div class="quiet-hour">
                    <label>结束时间:</label>
                    <input 
                      type="time" 
                      v-model="notificationSettings.quietHours.end" 
                      class="time-input"
                    />
                  </div>
                </div>
              </div>
              <div class="form-actions">
                <button type="button" @click="closeSettingsModal" class="cancel-btn">取消</button>
                <button type="submit" class="submit-btn">
                  <i v-if="updatingSettings" class="fa fa-spinner fa-spin"></i>
                  保存设置
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { notificationApi } from '../../api/notification';
import type { FrontendNotification, PersonalTask } from '../../api/notification';
import { useAuthStore } from '../../stores/auth';

// 使用认证状态管理
const authStore = useAuthStore();

// 响应式数据
const notifications = ref<FrontendNotification[]>([]);
const personalTasks = ref<PersonalTask[]>([]);
const activeFilter = ref('all');
const loading = ref(false);
const error = ref<string | null>(null);
const unreadCount = ref(0);

// 个人任务相关状态
const showCompletedTasks = ref(false);

// 模态框状态
const showEditTaskModal = ref(false);
const showSettingsModal = ref(false);
const updatingSettings = ref(false);

// 新建任务
const newTaskTitle = ref('');
const newTaskDueDate = ref('');
const newTaskPriority = ref('medium');

// 编辑任务
const editingTask = ref<Partial<PersonalTask>>({});

// 定时器
let deadlineCheckInterval: NodeJS.Timeout | null = null;
let notificationUpdateInterval: NodeJS.Timeout | null = null;
let websocket: WebSocket | null = null;

// 筛选器配置
const filters = [
  { key: 'all', label: '全部', icon: 'fa fa-list' },
  { key: 'unread', label: '未读', icon: 'fa fa-eye-slash' },
  { key: 'task', label: '任务', icon: 'fa fa-tasks' },
  { key: 'deadline', label: 'DDL提醒', icon: 'fa fa-clock-o' },
  { key: 'course', label: '课程通知', icon: 'fa fa-graduation-cap' },
  { key: 'system', label: '系统通知', icon: 'fa fa-cog' }
];

// 计算属性
const filteredNotifications = computed(() => {
  let filtered = notifications.value;
  
  switch (activeFilter.value) {
    case 'unread':
      filtered = filtered.filter(n => !n.read);
      break;
    case 'task':
    case 'deadline':
    case 'course':
    case 'system':
      filtered = filtered.filter(n => n.type === activeFilter.value);
      break;
  }
  
  return filtered.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
});

const filteredPersonalTasks = computed(() => {
  let filtered = personalTasks.value;
  
  if (!showCompletedTasks.value) {
    filtered = filtered.filter(task => !task.completed);
  }
  
  return filtered.sort((a, b) => {
    // 优先显示未完成的任务
    if (a.completed !== b.completed) {
      return a.completed ? 1 : -1;
    }
    
    // 按优先级排序
    const priorityOrder = { high: 3, medium: 2, low: 1 };
    if (a.priority !== b.priority) {
      return priorityOrder[b.priority] - priorityOrder[a.priority];
    }
    
    // 按截止日期排序
    if (a.dueDate && b.dueDate) {
      return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime();
    }
    
    return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
  });
});

const incompleteTasks = computed(() => 
  personalTasks.value.filter(task => !task.completed).length
);

// 工具函数
const getTypeIcon = (type: string) => {
  const icons = {
    task: 'fa fa-tasks',
    deadline: 'fa fa-clock-o',
    course: 'fa fa-graduation-cap',
    system: 'fa fa-cog',
    assignment: 'fa fa-file-text-o'
  };
  return icons[type as keyof typeof icons] || 'fa fa-bell';
};

const getTypeLabel = (type: string) => {
  const labels = {
    task: '新任务',
    deadline: 'DDL提醒',
    course: '课程通知',
    system: '系统通知',
    assignment: '作业通知'
  };
  return labels[type as keyof typeof labels] || '通知';
};

const getSenderRoleLabel = (role: string) => {
  const labels = {
    teacher: '教师',
    assistant: '助教',
    system: '系统'
  };
  return labels[role as keyof typeof labels] || '';
};

const getPriorityLabel = (priority: string) => {
  const labels = {
    low: '低',
    medium: '中',
    high: '高'
  };
  return labels[priority as keyof typeof labels] || '中';
};

const formatDate = (dateString: string) => {
  if (!dateString) return '未知日期';
  
  const date = new Date(dateString);
  const now = new Date();
  const diffInHours = (now.getTime() - date.getTime()) / (1000 * 60 * 60);
  
  if (diffInHours < 1) {
    return '刚刚';
  } else if (diffInHours < 24) {
    return `${Math.floor(diffInHours)}小时前`;
  } else if (diffInHours < 48) {
    return '昨天';
  } else {
    return date.toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }
};

const getDueDateClass = (dueDate: string) => {
  if (!dueDate) return 'normal';
  
  const due = new Date(dueDate);
  const now = new Date();
  const diffInDays = (due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24);
  
  if (diffInDays < 0) {
    return 'urgent'; // 已过期
  } else if (diffInDays < 1) {
    return 'urgent'; // 今天截止
  } else if (diffInDays < 3) {
    return 'warning'; // 3天内截止
  }
  return 'normal';
};

const isTaskOverdue = (task: PersonalTask) => {
  if (!task.dueDate || task.completed) return false;
  return new Date(task.dueDate) < new Date();
};

const getFilterCount = (filterKey: string) => {
  if (filterKey === 'all') return notifications.value.length;
  if (filterKey === 'unread') return notifications.value.filter(n => !n.read).length;
  return notifications.value.filter(n => n.type === filterKey).length;
};

const getEmptyMessage = () => {
  switch (activeFilter.value) {
    case 'unread':
      return '没有未读通知';
    case 'task':
      return '没有新任务';
    case 'deadline':
      return '没有DDL提醒';
    case 'course':
      return '没有课程通知';
    case 'system':
      return '没有系统通知';
    default:
      return '暂无通知';
  }
};

// 通知操作
const markAsRead = async (id: number) => {
  try {
    await notificationApi.markAsRead(id);
    const notification = notifications.value.find(n => n.id === id);
    if (notification && !notification.read) {
      notification.read = true;
      unreadCount.value = Math.max(0, unreadCount.value - 1);
    }
  } catch (err) {
    console.error('标记通知已读失败:', err);
    error.value = '标记已读失败，请重试';
    // 在实际应用中可以显示 toast 提示
  }
};

const markAllAsRead = async () => {
  try {
    const unreadIds = notifications.value.filter(n => !n.read).map(n => n.id);
    if (unreadIds.length === 0) return;
    
    await notificationApi.markMultipleAsRead(unreadIds);
    notifications.value.forEach(n => {
      if (!n.read) n.read = true;
    });
    unreadCount.value = 0;
  } catch (err) {
    console.error('批量标记已读失败:', err);
    error.value = '批量标记已读失败，请重试';
  }
};

const deleteNotification = async (id: number) => {
  if (!confirm('确定要删除这条通知吗？')) return;
  
  try {
    await notificationApi.deleteNotification(id);
    const index = notifications.value.findIndex(n => n.id === id);
    if (index > -1) {
      const notification = notifications.value[index];
      if (!notification.read) {
        unreadCount.value = Math.max(0, unreadCount.value - 1);
      }
      notifications.value.splice(index, 1);
    }
  } catch (err) {
    console.error('删除通知失败:', err);
    error.value = '删除通知失败，请重试';
  }
};

const refreshNotifications = async () => {
  loading.value = true;
  try {
    await Promise.all([loadNotifications(), loadPersonalTasks()]);
    error.value = null; // 清除之前的错误
  } catch (err) {
    // 错误已在各自的加载函数中处理
  } finally {
    loading.value = false;
  }
};

// 个人任务操作
const addPersonalTask = async () => {
  if (!newTaskTitle.value.trim()) {
    error.value = '任务标题不能为空';
    return;
  }
  
  try {
    const newTask: Omit<PersonalTask, 'id' | 'createdAt'> = {
      title: newTaskTitle.value.trim(),
      completed: false,
      priority: newTaskPriority.value as any,
      dueDate: newTaskDueDate.value || undefined
    };
    
    const createdTask = await notificationApi.createPersonalTask(newTask);
    personalTasks.value.unshift(createdTask);
    
    // 清空输入
    newTaskTitle.value = '';
    newTaskDueDate.value = '';
    newTaskPriority.value = 'medium';
    error.value = null;
  } catch (err) {
    console.error('添加任务失败:', err);
    error.value = '添加任务失败，请重试';
  }
};

const updatePersonalTask = async (task: PersonalTask) => {
  try {
    await notificationApi.updatePersonalTask(task.id, { completed: task.completed });
    
    // 如果任务完成且有关联的通知，自动删除相关通知
    if (task.completed && task.linkedNotificationId) {
      await notificationApi.autoDeleteOnTaskCompletion(task.linkedNotificationId.toString());
      // 重新加载通知列表以反映变化
      await loadNotifications();
    }
  } catch (err) {
    console.error('更新任务失败:', err);
    error.value = '更新任务失败，请重试';
    // 回滚状态
    task.completed = !task.completed;
  }
};

const editPersonalTask = (task: PersonalTask) => {
  editingTask.value = { ...task };
  showEditTaskModal.value = true;
};

const saveEditedTask = async () => {
  if (!editingTask.value.id || !editingTask.value.title?.trim()) {
    error.value = '任务标题不能为空';
    return;
  }
  
  try {
    const updatedTask = await notificationApi.updatePersonalTask(editingTask.value.id, editingTask.value);
    const index = personalTasks.value.findIndex(t => t.id === editingTask.value.id);
    if (index > -1) {
      personalTasks.value[index] = updatedTask;
    }
    closeEditTaskModal();
    error.value = null;
  } catch (err) {
    console.error('保存任务失败:', err);
    error.value = '保存任务失败，请重试';
  }
};

const closeEditTaskModal = () => {
  showEditTaskModal.value = false;
  editingTask.value = {};
};

const deletePersonalTask = async (id: number) => {
  if (!confirm('确定要删除这个任务吗？')) return;
  
  try {
    await notificationApi.deletePersonalTask(id);
    const index = personalTasks.value.findIndex(t => t.id === id);
    if (index > -1) {
      personalTasks.value.splice(index, 1);
    }
    error.value = null;
  } catch (err) {
    console.error('删除任务失败:', err);
    error.value = '删除任务失败，请重试';
  }
};

// 通知设置相关
const notificationSettings = ref({
  enablePush: true,
  enableEmail: false,
  enableDeadlineReminders: true,
  reminderDays: [3, 1], // 提前3天和1天提醒
  quietHours: {
    enabled: false,
    start: '22:00',
    end: '08:00'
  }
});

const closeSettingsModal = () => {
  showSettingsModal.value = false;
};

// 加载通知设置（从本地存储）
const loadNotificationSettingsFromLocal = () => {
  try {
    const stored = localStorage.getItem('notificationSettings');
    if (stored) {
      const settings = JSON.parse(stored);
      notificationSettings.value = { ...notificationSettings.value, ...settings };
    }
  } catch (err) {
    console.error('加载通知设置失败:', err);
  }
};

// 保存通知设置（到本地存储）
const saveNotificationSettings = async () => {
  try {
    localStorage.setItem('notificationSettings', JSON.stringify(notificationSettings.value));
    closeSettingsModal();
    // 可以在这里添加成功提示
    console.log('通知设置已保存');
  } catch (err) {
    console.error('保存通知设置失败:', err);
    error.value = '保存设置失败，请重试';
  }
};

// 批量操作
const selectedNotifications = ref<number[]>([]);
const showBatchActions = computed(() => selectedNotifications.value.length > 0);

// 切换通知选择
const toggleNotificationSelection = (notificationId: number) => {
  const index = selectedNotifications.value.indexOf(notificationId);
  if (index > -1) {
    selectedNotifications.value.splice(index, 1);
  } else {
    selectedNotifications.value.push(notificationId);
  }
};

// 全选/取消全选
const toggleSelectAll = () => {
  if (selectedNotifications.value.length === filteredNotifications.value.length) {
    selectedNotifications.value = [];
  } else {
    selectedNotifications.value = filteredNotifications.value.map(n => n.id);
  }
};

// 批量删除选中的通知
const deleteSelectedNotifications = async () => {
  if (selectedNotifications.value.length === 0) return;
  
  if (!confirm(`确定要删除选中的 ${selectedNotifications.value.length} 条通知吗？`)) return;
  
  try {
    // 并行删除所有选中的通知
    await Promise.all(
      selectedNotifications.value.map(id => notificationApi.deleteNotification(id))
    );
    
    // 更新本地状态
    selectedNotifications.value.forEach(id => {
      const index = notifications.value.findIndex(n => n.id === id);
      if (index > -1) {
        const notification = notifications.value[index];
        if (!notification.read) {
          unreadCount.value = Math.max(0, unreadCount.value - 1);
        }
        notifications.value.splice(index, 1);
      }
    });
    
    selectedNotifications.value = [];
    error.value = null;
  } catch (err) {
    console.error('批量删除通知失败:', err);
    error.value = '批量删除失败，请重试';
  }
};

// 批量标记选中通知为已读
const markSelectedAsRead = async () => {
  if (selectedNotifications.value.length === 0) return;
  
  try {
    const unreadSelectedIds = selectedNotifications.value.filter(id => {
      const notification = notifications.value.find(n => n.id === id);
      return notification && !notification.read;
    });
    
    if (unreadSelectedIds.length === 0) return;
    
    await notificationApi.markMultipleAsRead(unreadSelectedIds);
    
    // 更新本地状态
    unreadSelectedIds.forEach(id => {
      const notification = notifications.value.find(n => n.id === id);
      if (notification && !notification.read) {
        notification.read = true;
        unreadCount.value = Math.max(0, unreadCount.value - 1);
      }
    });
    
    selectedNotifications.value = [];
    error.value = null;
  } catch (err) {
    console.error('批量标记已读失败:', err);
    error.value = '批量标记已读失败，请重试';
  }
};

// 数据加载
const loadNotifications = async () => {
  try {
    error.value = null;
    const data = await notificationApi.getNotifications();
    notifications.value = data;
    unreadCount.value = await notificationApi.getUnreadCount();
  } catch (err) {
    console.error('加载通知失败:', err);
    error.value = '加载通知失败，请检查网络连接后重试';
    notifications.value = [];
    unreadCount.value = 0;
    throw err;
  }
};

const loadPersonalTasks = async () => {
  try {
    // 从 authStore 获取 userId
    const userId = authStore.user?.id;
    if (!userId) {
      console.error('用户未登录，无法加载个人任务');
      personalTasks.value = [];
      return;
    }
    const data = await notificationApi.getPersonalTasks(userId);
    personalTasks.value = data;
  } catch (err) {
    console.error('加载个人任务失败:', err);
    personalTasks.value = [];
    throw err;
  }
};

// DDL检查和提醒生成
const checkDeadlinesAndGenerateReminders = async () => {
  try {
    await notificationApi.checkDeadlinesAndGenerateReminders();
    await loadNotifications(); // 重新加载通知以获取新生成的提醒
  } catch (err) {
    console.error('检查DDL失败:', err);
  }
};

// 实时通知更新
const initRealtimeNotifications = () => {
  // 如果支持WebSocket，使用WebSocket进行实时更新
  if (typeof WebSocket !== 'undefined') {
    try {
      // 从环境变量获取WebSocket URL，回退到默认值
      const wsUrl = process.env.NODE_ENV === 'development' 
        ? 'ws://localhost:3000/notifications' 
        : 'wss://your-production-domain.com/notifications';
      
      websocket = new WebSocket(wsUrl);
      
      websocket.onopen = () => {
        console.log('WebSocket连接已建立');
        // 发送用户认证信息
        if (authStore.user) {
          websocket?.send(JSON.stringify({
            type: 'auth',
            userId: authStore.user.id,
            token: authStore.token
          }));
        }
      };
      
      websocket.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          handleRealtimeNotification(data);
        } catch (err) {
          console.error('处理WebSocket消息失败:', err);
        }
      };
      
      websocket.onerror = (error) => {
        console.error('WebSocket错误:', error);
        // 回退到轮询模式
        setupPollingMode();
      };
      
      websocket.onclose = () => {
        console.log('WebSocket连接已关闭');
        // 尝试重连或回退到轮询模式
        setTimeout(() => {
          if (!websocket || websocket.readyState === WebSocket.CLOSED) {
            setupPollingMode();
          }
        }, 5000);
      };
    } catch (err) {
      console.error('WebSocket连接失败:', err);
      setupPollingMode();
    }
  } else {
    // 不支持WebSocket，使用轮询
    setupPollingMode();
  }
};

// 设置轮询模式
const setupPollingMode = () => {
  // 每30秒轮询一次新通知
  notificationUpdateInterval = setInterval(async () => {
    try {
      const currentUnreadCount = await notificationApi.getUnreadCount();
      if (currentUnreadCount > unreadCount.value) {
        // 有新通知，重新加载
        await loadNotifications();
      }
    } catch (err) {
      console.error('轮询通知失败:', err);
    }
  }, 30000);
};

// 处理实时通知
const handleRealtimeNotification = (data: any) => {
  switch (data.type) {
    case 'new_notification':
      // 新通知
      notifications.value.unshift(data.notification);
      unreadCount.value++;
      break;
    case 'notification_read':
      // 通知已读
      const readNotification = notifications.value.find(n => n.id === data.notificationId);
      if (readNotification && !readNotification.read) {
        readNotification.read = true;
        unreadCount.value = Math.max(0, unreadCount.value - 1);
      }
      break;
    case 'notification_deleted':
      // 通知删除
      const deleteIndex = notifications.value.findIndex(n => n.id === data.notificationId);
      if (deleteIndex > -1) {
        const deletedNotification = notifications.value[deleteIndex];
        if (!deletedNotification.read) {
          unreadCount.value = Math.max(0, unreadCount.value - 1);
        }
        notifications.value.splice(deleteIndex, 1);
      }
      break;
    case 'unread_count_update':
      // 未读数量更新
      unreadCount.value = data.count;
      break;
  }
};

// 清理连接
const cleanupRealtimeConnections = () => {
  if (websocket && websocket.readyState === WebSocket.OPEN) {
    websocket.close();
  }
  if (notificationUpdateInterval) {
    clearInterval(notificationUpdateInterval);
  }
  if (deadlineCheckInterval) {
    clearInterval(deadlineCheckInterval);
  }
};

// 生命周期
onMounted(async () => {
  loading.value = true;
  error.value = null;
  
  try {
    // 确保用户已登录
    if (!authStore.user) {
      error.value = '请先登录';
      return;
    }
    
    await Promise.all([loadNotifications(), loadPersonalTasks()]);
    
    // 设置定时检查DDL（每小时检查一次）
    deadlineCheckInterval = setInterval(checkDeadlinesAndGenerateReminders, 60 * 60 * 1000);
      // 初始化实时通知
    initRealtimeNotifications();
    
    // 加载通知设置从本地存储
    loadNotificationSettingsFromLocal();
  } catch (err) {
    console.error('初始化通知页面失败:', err);
    error.value = '加载数据失败，请刷新页面重试';
  } finally {
    loading.value = false;
  }
});

onUnmounted(() => {
  cleanupRealtimeConnections();
});

// 监听器
watch(activeFilter, () => {
  // 可以在这里添加筛选器变化时的逻辑
});
</script>

<style scoped>
.notification-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  background-color: var(--bg-secondary);
  border-radius: 8px;
  box-shadow: var(--shadow-md);
  transition: background-color var(--transition-normal);
}

/* 工具栏 */
.toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid var(--border-color);
}

.toolbar-left {
  display: flex;
  align-items: center;
}

.toolbar-right {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.title {
  font-size: 24px;
  color: var(--primary);
  margin: 0;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.action-buttons {
  display: flex;
  gap: 0.5rem;
}

.action-btn {
  padding: 0.5rem 0.75rem;
  border: 1px solid var(--border-color);
  background-color: var(--bg-primary);
  color: var(--text-secondary);
  border-radius: 4px;
  cursor: pointer;
  transition: all var(--transition-fast);
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.875rem;
}

.action-btn:hover:not(:disabled) {
  background-color: var(--bg-tertiary);
  color: var(--text-primary);
}

.action-btn:disabled {
  opacity: 0.5;  cursor: not-allowed;
}

.badge {
  background-color: var(--danger);
  color: white;
  border-radius: 50%;
  width: 20px;
  height: 20px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-size: 0.75rem;
  margin-left: 0.5rem;
  padding: 0.25rem 0.5rem;
  font-weight: bold;
  min-width: 20px;
  text-align: center;
}

/* 筛选标签 */
.filter-tabs {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
}

.filter-tab {
  padding: 0.5rem 1rem;
  border: 1px solid var(--border-color);
  background-color: var(--bg-secondary);
  color: var(--text-secondary);
  border-radius: 25px;
  cursor: pointer;
  transition: all var(--transition-fast);
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.875rem;
}

.filter-tab:hover {
  background-color: var(--bg-tertiary);
  color: var(--text-primary);
}

.filter-tab.active {
  background-color: var(--primary);
  color: white;
  border-color: var(--primary);
}

.filter-count {
  background-color: rgba(0, 0, 0, 0.1);
  padding: 0.1rem 0.4rem;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: 500;
}

.filter-toggle {
  background-color: transparent;
  border: 1px solid var(--border-color);
  color: var(--text-secondary);
  border-radius: 20px;
  padding: 0.4rem 0.75rem;
  font-size: 0.875rem;
  cursor: pointer;
  transition: all var(--transition-fast);
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.filter-toggle:hover {
  background-color: var(--bg-tertiary);
}

.filter-toggle.active {
  background-color: var(--primary-light);
  color: var(--primary);
  border-color: var(--primary);
}

/* 章节标题 */
.section {
  margin-bottom: 2rem;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.section-title {
  font-size: 1.25rem;
  color: var(--text-primary);
  margin: 0;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.task-badge {
  background-color: var(--primary);
  color: white;
  font-size: 0.75rem;
  padding: 0.1rem 0.4rem;
  border-radius: 12px;
}

/* 通知列表 */
.notification-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.notification-card {
  padding: 1.5rem;
  background-color: var(--bg-primary);
  border: 1px solid var(--border-color);
  border-radius: 12px;
  box-shadow: var(--shadow-sm);
  transition: all var(--transition-normal);
  position: relative;
}

.notification-card:hover {
  background-color: var(--bg-tertiary);
  box-shadow: var(--shadow-md);
  transform: translateY(-1px);
}

.notification-card.unread {
  border-left: 4px solid var(--primary);
}

.notification-card.high {
  border-left-color: #ff4444;
}

.notification-card.medium {
  border-left-color: #ffa500;
}

.notification-card.low {
  border-left-color: #28a745;
}

.notification-card.urgent {
  border-left-color: #dc3545;
  background-color: rgba(220, 53, 69, 0.05);
}

.notification-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 0.75rem;
}

.notification-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  align-items: center;
  font-size: 0.875rem;
}

.notification-type {
  background-color: var(--bg-tertiary);
  color: var(--text-secondary);
  padding: 0.25rem 0.5rem;
  border-radius: 4px;
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.course-name {
  font-weight: 500;
  color: var(--text-secondary);
}

.sender-role {
  color: var(--text-tertiary);
  font-style: italic;
}

.notification-actions {
  display: flex;
  gap: 0.5rem;
}

.mark-read-btn, .delete-btn {
  background-color: transparent;
  border: none;
  padding: 0.25rem;
  cursor: pointer;
  color: var(--text-tertiary);
  border-radius: 4px;
  transition: all var(--transition-fast);
}

.mark-read-btn:hover {
  color: var(--primary);
  background-color: var(--bg-tertiary);
}

.delete-btn:hover {
  color: var(--danger);
  background-color: var(--bg-tertiary);
}

.notification-title {
  font-size: 1.25rem;
  color: var(--text-primary);
  margin-bottom: 0.75rem;
  font-weight: 600;
}

.notification-content {
  font-size: 1rem;
  color: var(--text-secondary);
  margin-bottom: 1rem;
  line-height: 1.5;
}

.notification-tags {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
  margin-bottom: 1rem;
}

.tag {
  background-color: var(--bg-tertiary);
  color: var(--text-secondary);
  padding: 0.25rem 0.5rem;
  border-radius: 4px;
  font-size: 0.875rem;
}

.notification-footer {
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-end;
  align-items: center;
  gap: 1rem;
  margin-top: 0.5rem;
}

.notification-date {
  font-size: 0.875rem;
  color: var(--text-tertiary);
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.due-date {
  font-size: 0.875rem;
  display: flex;
  align-items: center;
  gap: 0.25rem;
  padding: 0.25rem 0.5rem;
  border-radius: 4px;
  font-weight: 500;
}

.due-date.normal {
  background-color: var(--bg-tertiary);
  color: var(--text-secondary);
}

.due-date.warning {
  background-color: #fff3cd;
  color: #856404;
}

.due-date.urgent {
  background-color: #f8d7da;
  color: #721c24;
  animation: pulse 2s infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.7; }
}

.task-link {
  color: var(--primary);
  text-decoration: none;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.875rem;
}

.task-link:hover {
  text-decoration: underline;
}

.auto-tag {
  background-color: #6c757d;
  color: white;
  font-size: 0.7rem;
  padding: 0.1rem 0.3rem;
  border-radius: 4px;
  margin-left: 0.25rem;
}

.no-notifications, .no-tasks {
  text-align: center;
  color: var(--text-tertiary);
  font-size: 16px;
  padding: 3rem 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
}

/* 错误提示 */
.error-message {
  background-color: #f8d7da;
  color: #721c24;
  padding: 1rem;
  border-radius: 4px;
  margin-bottom: 1rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  border: 1px solid #f5c6cb;
}

.error-message i {
  margin-right: 0.5rem;
}

.close-error {
  background-color: transparent;
  border: none;
  color: #721c24;
  cursor: pointer;
  padding: 0.25rem;
  border-radius: 2px;
}

.close-error:hover {
  background-color: rgba(114, 28, 36, 0.1);
}

/* 加载状态 */
.loading-state {
  text-align: center;
  padding: 3rem 0;
  color: var(--text-secondary);
}

.loading-state i {
  margin-bottom: 1rem;
}

/* 任务输入区域 */
.task-input {
  display: flex;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
}

.task-input-field {
  flex: 2;
  padding: 0.75rem;
  border: 1px solid var(--border-color);
  border-radius: 8px;
  background-color: var(--bg-primary);
  color: var(--text-primary);
  font-size: 1rem;
  transition: all var(--transition-fast);
}

.task-date-input {
  flex: 1;
  min-width: 200px;
  padding: 0.75rem;
  border: 1px solid var(--border-color);
  border-radius: 8px;
  background-color: var(--bg-primary);
  color: var(--text-primary);
  transition: all var(--transition-fast);
}

.task-priority-select {
  width: auto;
  padding: 0.75rem;
  border: 1px solid var(--border-color);
  border-radius: 8px;
  background-color: var(--bg-primary);
  color: var(--text-primary);
  cursor: pointer;
}

.task-input-field:focus, .task-date-input:focus, .task-priority-select:focus {
  border-color: var(--primary);
  outline: none;
  box-shadow: 0 0 0 3px rgba(44, 110, 207, 0.1);
}

.add-task-btn {
  padding: 0.75rem 1.5rem;
  background-color: var(--primary);
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 500;
  transition: background-color var(--transition-fast);
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.add-task-btn:hover:not(:disabled) {
  background-color: var(--primary-dark);
}

.add-task-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* 个人任务列表 */
.personal-task-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.personal-task-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem;
  background-color: var(--bg-primary);
  border: 1px solid var(--border-color);
  border-radius: 8px;
  transition: all var(--transition-normal);
  position: relative;
}

.personal-task-item:hover {
  background-color: var(--bg-tertiary);
  transform: translateY(-1px);
  box-shadow: var(--shadow-sm);
}

.personal-task-item.completed {
  opacity: 0.7;
  background-color: var(--bg-secondary);
}

.personal-task-item.completed .task-title {
  text-decoration: line-through;
}

.personal-task-item.high {
  border-left: 4px solid #ff4444;
}

.personal-task-item.medium {
  border-left: 4px solid #ffa500;
}

.personal-task-item.low {
  border-left: 4px solid #28a745;
}

.personal-task-item.overdue:not(.completed) {
  background-color: rgba(255, 68, 68, 0.05);
}

.task-checkbox {
  position: relative;
}

.task-checkbox input[type="checkbox"] {
  opacity: 0;
  position: absolute;
}

.checkbox-label {
  display: block;
  width: 20px;
  height: 20px;
  border: 2px solid var(--border-color);
  border-radius: 4px;
  cursor: pointer;
  transition: all var(--transition-fast);
  position: relative;
}

.task-checkbox input[type="checkbox"]:checked + .checkbox-label {
  background-color: var(--primary);
  border-color: var(--primary);
}

.task-checkbox input[type="checkbox"]:checked + .checkbox-label::after {
  content: '✓';
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
  font-size: 12px;
  font-weight: bold;
}

.task-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.task-title {
  font-weight: 500;
  color: var(--text-primary);
}

.task-description {
  font-size: 0.875rem;
  color: var(--text-secondary);
}

.task-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  margin-top: 0.25rem;
  align-items: center;
  font-size: 0.75rem;
  color: var(--text-tertiary);
}

.task-date {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  color: var(--text-tertiary);
}

.task-due-date {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  background-color: var(--bg-tertiary);
}

.task-due-date.overdue {
  background-color: #f8d7da;
  color: #721c24;
}

.task-priority-indicator {
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 500;
}

.task-priority-indicator.high {
  background-color: rgba(255, 68, 68, 0.1);
  color: #ff4444;
}

.task-priority-indicator.medium {
  background-color: rgba(255, 165, 0, 0.1);
  color: #ffa500;
}

.task-priority-indicator.low {
  background-color: rgba(40, 167, 69, 0.1);
  color: #28a745;
}

.task-actions {
  display: flex;
  gap: 0.5rem;
}

.edit-task-btn, .delete-task-btn {
  background-color: transparent;
  border: none;
  padding: 0.3rem;
  cursor: pointer;
  border-radius: 4px;
  color: var(--text-tertiary);
  transition: all var(--transition-fast);
}

.edit-task-btn:hover {
  background-color: var(--bg-tertiary);
  color: var(--primary);
}

.delete-task-btn:hover {
  background-color: var(--bg-tertiary);
  color: var(--danger);
}

/* 模态框样式 */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background-color: var(--bg-primary);
  border-radius: 8px;
  box-shadow: var(--shadow-lg);
  width: 90%;
  max-width: 600px;
  max-height: 90vh;
  overflow-y: auto;
}

.modal-header {
  padding: 1rem;
  border-bottom: 1px solid var(--border-color);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.modal-header h3 {
  margin: 0;
  color: var(--text-primary);
  font-size: 1.25rem;
}

.modal-close {
  background-color: transparent;
  border: none;
  font-size: 1.25rem;
  cursor: pointer;
  color: var(--text-tertiary);
  padding: 0.25rem;
}

.modal-close:hover {
  color: var(--danger);
}

.modal-body {
  padding: 1rem;
}

.form-group {
  margin-bottom: 1rem;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  color: var(--text-secondary);
  font-size: 0.875rem;
}

.form-group input, .form-group select, .form-group textarea {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid var(--border-color);
  border-radius: 4px;
  background-color: var(--bg-primary);
  color: var(--text-primary);
  font-size: 1rem;
}

.form-group input:focus, .form-group select:focus, .form-group textarea:focus {
  outline: none;
  border-color: var(--primary);
  box-shadow: 0 0 0 3px rgba(44, 110, 207, 0.1);
}

.form-actions {
  display: flex;
  justify-content: flex-end;
  gap: 1rem;
  margin-top: 1.5rem;
}

.cancel-btn {
  padding: 0.75rem 1.5rem;
  background-color: var(--bg-tertiary);
  color: var(--text-secondary);
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-weight: 500;
}

.submit-btn {
  padding: 0.75rem 1.5rem;
  background-color: var(--primary);
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-weight: 500;
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
}

.cancel-btn:hover {
  background-color: var(--bg-quaternary);
}

.submit-btn:hover:not(:disabled) {
  background-color: var(--primary-dark);
}

/* 批量操作样式 */
.batch-actions-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: var(--primary);
  color: white;
  padding: 0.75rem 1rem;
  border-radius: 6px;
  margin-bottom: 1rem;
  box-shadow: var(--shadow-sm);
}

.batch-info {
  display: flex;
  align-items: center;
  gap: 1rem;
  font-size: 0.875rem;
}

.clear-selection {
  background: none;
  border: none;
  color: white;
  cursor: pointer;
  padding: 0.25rem;
  border-radius: 4px;
  display: flex;
  align-items: center;
  gap: 0.25rem;
  transition: background-color var(--transition-fast);
}

.clear-selection:hover {
  background-color: rgba(255, 255, 255, 0.1);
}

.batch-buttons {
  display: flex;
  gap: 0.5rem;
}

.batch-btn {
  background-color: rgba(255, 255, 255, 0.1);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: white;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.875rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  transition: all var(--transition-fast);
}

.batch-btn:hover {
  background-color: rgba(255, 255, 255, 0.2);
}

.batch-btn.delete:hover {
  background-color: var(--danger);
  border-color: var(--danger);
}

.selection-toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
  padding: 0.5rem;
  background-color: var(--bg-tertiary);
  border-radius: 6px;
}

.selection-controls {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.select-all-btn {
  background: none;
  border: none;
  color: var(--primary);
  cursor: pointer;
  padding: 0.5rem;
  border-radius: 4px;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.875rem;
  transition: background-color var(--transition-fast);
}

.select-all-btn:hover {
  background-color: var(--bg-quaternary);
}

/* 通知卡片复选框样式 */
.notification-card {
  display: flex;
  align-items: flex-start;
  gap: 1rem;
  transition: all var(--transition-fast);
}

.notification-card.selected {
  background-color: rgba(44, 110, 207, 0.05);
  border-left: 4px solid var(--primary);
}

.notification-checkbox {
  display: flex;
  align-items: center;
  margin-top: 0.5rem;
}

.notification-checkbox input[type="checkbox"] {
  display: none;
}

.notification-checkbox .checkbox-label {
  display: block;
  width: 18px;
  height: 18px;
  border: 2px solid var(--border-color);
  border-radius: 4px;
  cursor: pointer;
  transition: all var(--transition-fast);
  position: relative;
}

.notification-checkbox input[type="checkbox"]:checked + .checkbox-label {
  background-color: var(--primary);
  border-color: var(--primary);
}

.notification-checkbox input[type="checkbox"]:checked + .checkbox-label::after {
  content: '✓';
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
  font-size: 11px;
  font-weight: bold;
}

.notification-content-wrapper {
  flex: 1;
  cursor: pointer;
}

/* 通知设置样式 */
.toggle-checkbox {
  width: auto !important;
  margin-right: 0.5rem;
}

.toggle-label {
  font-size: 0.875rem;
  color: var(--text-secondary);
}

.reminder-times {
  display: flex;
  gap: 1rem;
  margin-top: 0.5rem;
}

.reminder-time {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.reminder-input {
  width: 80px !important;
  text-align: center;
}

.reminder-unit {
  font-size: 0.875rem;
  color: var(--text-secondary);
}

.quiet-hours-settings {
  margin-top: 0.5rem;
  padding-top: 0.5rem;
  border-top: 1px solid var(--border-color);
}

.quiet-hour {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 0.5rem;
}

.quiet-hour label {
  min-width: 80px;
  margin-bottom: 0;
}

.time-input {
  width: 120px !important;
}

.submit-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* 响应式适配 */
@media (max-width: 768px) {
  .notification-container {
    padding: 1rem;
  }
  
  .toolbar {
    flex-direction: column;
    gap: 1rem;
  }
  
  .toolbar-right {
    width: 100%;
    justify-content: space-between;
  }
  
  .filter-tabs {
    justify-content: center;
  }
  
  .notification-header {
    flex-direction: column;
    gap: 1rem;
  }
  
  .notification-footer {
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }
  
  .task-input {
    flex-direction: column;
  }
  
  .personal-task-item {
    flex-direction: column;
    align-items: flex-start;
    gap: 0.75rem;
  }
  
  .task-actions {
    position: absolute;
    top: 0.5rem;
    right: 0.5rem;
  }
}
</style>