
### 文件上传测试
POST http://localhost:8080/api/courses/1/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Java编程.pdf"
Content-Type: application/pdf

< ./Java编程.pdf
--WebAppBoundary
Content-Disposition: form-data; name="title"

Java编程
--WebAppBoundary
Content-Disposition: form-data; name="sectionId"

1
--WebAppBoundary
Content-Disposition: form-data; name="uploaderId"

1
--WebAppBoundary
Content-Disposition: form-data; name="visibility"

CLASS_ONLY
--WebAppBoundary
Content-Disposition: form-data; name="type"

PDF
--WebAppBoundary--


### 获取文件列表
POST http://localhost:8080/api/courses/1/filelist
Content-Type: application/json

{   
    "userId":1,
    "courseId":1,
    "chapter":1,
    "type":"PDF",
    "title":""
}

### 获取文件下载URL
GET http://localhost:8080/api/resources/3/download-url

