### 1. 创建作业 
### 创建作业
POST http://localhost:8080/api/homework/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="class_id"

1

--WebAppBoundary
Content-Disposition: form-data; name="title"

第一次作业

--WebAppBoundary
Content-Disposition: form-data; name="description"

请完成课后第3题到第6题

--WebAppBoundary
Content-Disposition: form-data; name="end_time"

2025-06-10 23:59:59
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="homework1.pdf"
Content-Type: application/pdf

< ./files/homework1.pdf
--WebAppBoundary--



### 3. 获取班级作业列表
GET http://localhost:8080/api/homework/list?class_id=1
Content-Type: application/json

### 4. 提交作业
POST http://localhost:8080/api/homework/submit/7
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="student_id"

2

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="submission1.pdf"
Content-Type: application/pdf

< ./files/submission1.pdf
--WebAppBoundary--

### 5. 获取作业提交列表
GET http://localhost:8080/api/homework/submissions/7

