### 用户登录
POST http://localhost:8080/api/user/login
Content-Type: application/x-www-form-urlencoded

userId=u111&password=password123

### 查询学习记录
GET http://localhost:8080/record/study
Authorization: Bearer {{login.response.data.token}}
 
### 查询练习记录
GET http://localhost:8080/record/practice
Authorization: Bearer {{login.response.data.token}}
 
### 导出学习记录
GET http://localhost:8080/record/study/export
Authorization: Bearer {{login.response.data.token}}

### 导出练习记录
GET http://localhost:8080/record/practice/export
Authorization: Bearer {{login.response.data.token}}
 
### 查询练习报告
GET http://localhost:8080/record/practice/1/report
Authorization: Bearer {{login.response.data.token}}
 
### 导出练习报告
GET ://localhost:8080/record/practice/export-report/1 
Authorization: Bearer {{login.response.data.token}}
 