/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    Background: typeof import('./src/components/layout/Background.vue')['default']
    Calendar: typeof import('./src/components/littlecomponents/Calendar.vue')['default']
    ClassCard: typeof import('./src/components/class/ClassCard.vue')['default']
    ClassExerciseList: typeof import('./src/components/class/ClassExerciseList.vue')['default']
    ClassHomework: typeof import('./src/components/class/ClassHomework.vue')['default']
    ClassProcessing: typeof import('./src/components/class/ClassProcessing.vue')['default']
    ClassStudent: typeof import('./src/components/class/ClassStudent.vue')['default']
    CourseCard: typeof import('./src/components/course/CourseCard.vue')['default']
    CourseEditDialog: typeof import('./src/components/course/CourseEditDialog.vue')['default']
    CourseExerciseList: typeof import('./src/components/course/CourseExerciseList.vue')['default']
    CourseResourceList: typeof import('./src/components/course/CourseResourceList.vue')['default']
    CourseResourceUpload: typeof import('./src/components/course/CourseResourceUpload.vue')['default']
    CourseSyllabus: typeof import('./src/components/course/CourseSyllabus.vue')['default']
    CourseVideoList: typeof import('./src/components/course/CourseVideoList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageScroll: typeof import('./src/components/littlecomponents/ImageScroll.vue')['default']
    Knob: typeof import('./src/components/littlecomponents/knob.vue')['default']
    ProgressKnob: typeof import('./src/components/littlecomponents/ProgressKnob.vue')['default']
    ReplyForm: typeof import('./src/components/ReplyForm.vue')['default']
    ReplyItem: typeof import('./src/components/ReplyItem.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleKnob: typeof import('./src/components/littlecomponents/SimpleKnob.vue')['default']
    Theme: typeof import('./src/components/littlecomponents/Theme.vue')['default']
    ThemeToggle: typeof import('./src/components/littlecomponents/ThemeToggle.vue')['default']
    WriteBoard: typeof import('./src/components/littlecomponents/WriteBoard.vue')['default']
  }
}
