import axios from './axios';

<<<<<<< HEAD:frontend/project/src/api/notification.ts
// 通知类型定义（根据后端接口规范）
export interface Notification {
  id: number;
  title: string;
  message: string;
  type: 'PRACTICE_NOTICE' | 'HOMEWORK_NOTICE' | 'COURSE_NOTICE' | 'SYSTEM_NOTICE' | 'DEADLINE_REMINDER';
  readFlag: boolean;
  createdAt: string;
  relatedId?: number;
  relatedType?: 'PRACTICE' | 'HOMEWORK' | 'COURSE';
}

// 任务提醒类型定义
export interface TaskReminder {
  id: number;
  title: string;
  content: string;
  createTime: string;
  deadline: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  completed: boolean;
}

// 创建任务提醒请求类型
export interface CreateTaskReminderRequest {
  title: string;
  content: string;
  deadline: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
}

// 更新任务提醒请求类型
export interface UpdateTaskReminderRequest {
  title?: string;
  content?: string;
  deadline?: string;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
}

export const notificationApi = {
  // ========== 通知相关接口 ==========
  
  // 获取用户的所有通知
  getNotifications: async () => {
    const response = await axios.get('/api/notifications');
=======
// 通知类型定义
export interface Notification {
  id: number;
  type: 'task' | 'deadline' | 'system' | 'course' | 'assignment';
  title: string;
  content: string;
  courseName?: string;
  courseId?: string;
  createdAt: string;
  dueDate?: string;
  link?: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  read: boolean;
  senderRole?: 'teacher' | 'assistant' | 'system';
  senderId?: string;
  targetType?: 'individual' | 'class' | 'all';
  autoGenerated?: boolean;
  taskId?: string;
  tags?: string[];
}

// 个人任务类型定义
export interface PersonalTask {
  id: number;
  title: string;
  description?: string;
  completed: boolean;
  createdAt: string;
  dueDate?: string;
  priority: 'low' | 'medium' | 'high';
  tags?: string[];
  linkedNotificationId?: number;
}

// 任务分配信息
export interface TaskAssignment {
  id: string;
  title: string;
  description: string;
  courseId: string;
  courseName: string;
  dueDate: string;
  assignedBy: string;
  assignedTo: string[];
  link?: string;
  createdAt: string;
}

export const notificationApi = {
  // 获取通知列表
  getNotifications: async (params?: {
    type?: string;
    read?: boolean;
    courseId?: string;
    limit?: number;
    offset?: number;
  }) => {
    const response = await axios.get('/notifications', { params });
>>>>>>> 5468ddbcb29f92919cffedbc7b4859832e875670:qianduan/src/api/notification.ts
    return response.data;
  },

  // 获取未读通知数量
  getUnreadCount: async () => {
<<<<<<< HEAD:frontend/project/src/api/notification.ts
    const response = await axios.get('/api/notifications/unread');
    return response.data;
=======
    const response = await axios.get('/notifications/unread-count');
    return response.data.count;
>>>>>>> 5468ddbcb29f92919cffedbc7b4859832e875670:qianduan/src/api/notification.ts
  },

  // 标记通知为已读
  markAsRead: async (id: number) => {
<<<<<<< HEAD:frontend/project/src/api/notification.ts
    const response = await axios.put(`/api/notifications/${id}/read`);
    return response.data;
  },

  // 标记所有通知为已读
  markAllAsRead: async () => {
    const response = await axios.put('/api/notifications/read-all');
=======
    const response = await axios.patch(`/notifications/${id}/read`);
    return response.data;
  },

  // 批量标记为已读
  markMultipleAsRead: async (ids: number[]) => {
    const response = await axios.patch('/notifications/batch-read', { ids });
>>>>>>> 5468ddbcb29f92919cffedbc7b4859832e875670:qianduan/src/api/notification.ts
    return response.data;
  },

  // 删除通知
  deleteNotification: async (id: number) => {
<<<<<<< HEAD:frontend/project/src/api/notification.ts
    const response = await axios.delete(`/api/notifications/${id}`);
    return response.data;
  },

  // ========== 任务提醒相关接口 ==========
  
  // 创建任务提醒
  createTaskReminder: async (data: CreateTaskReminderRequest) => {
    const response = await axios.post('/api/task-reminders', data);
    return response.data;
  },

  // 更新任务提醒
  updateTaskReminder: async (id: number, data: UpdateTaskReminderRequest) => {
    const response = await axios.put(`/api/task-reminders/${id}`, data);
    return response.data;
  },

  // 获取任务提醒列表
  getTaskReminders: async (userId: number) => {
    const response = await axios.get(`/api/task-reminders/user/${userId}`);
    return response.data;
  },

  // 标记任务完成
  markTaskComplete: async (id: number) => {
    const response = await axios.put(`/api/task-reminders/${id}/complete`);
    return response.data;
  },

  // 标记任务未完成
  markTaskUncomplete: async (id: number) => {
    const response = await axios.put(`/api/task-reminders/${id}/uncomplete`);
    return response.data;
  },

  // 删除任务提醒
  deleteTaskReminder: async (id: number) => {
    const response = await axios.delete(`/api/task-reminders/${id}`);
    return response.data;
  },
  // ========== DDL自动提醒功能 ==========
  
  // 获取即将到期的任务（前端轮询用）
  getUpcomingDeadlines: async (days: number = 3) => {
    const response = await axios.get(`/api/task-reminders/upcoming?days=${days}`);
    return response.data;
  },

  // 检查并生成DDL提醒（系统调用）
  checkAndGenerateDeadlineReminders: async () => {
    const response = await axios.post('/api/notifications/auto-generate/deadline-reminders');
=======
    const response = await axios.delete(`/notifications/${id}`);
    return response.data;
  },

  // 创建通知（用于教师/助教）
  createNotification: async (notification: Omit<Notification, 'id' | 'createdAt'>) => {
    const response = await axios.post('/notifications', notification);
    return response.data;
  },

  // 自动生成任务分配通知
  generateTaskAssignmentNotification: async (taskAssignment: TaskAssignment) => {
    const response = await axios.post('/notifications/auto-generate/task-assignment', taskAssignment);
    return response.data;
  },

  // 自动生成DDL提醒
  generateDeadlineReminder: async (taskId: string, reminderDays: number[]) => {
    const response = await axios.post('/notifications/auto-generate/deadline-reminder', {
      taskId,
      reminderDays
    });
    return response.data;
  },

  // 任务完成时自动删除相关通知
  autoDeleteOnTaskCompletion: async (taskId: string) => {
    const response = await axios.delete(`/notifications/auto-delete/task/${taskId}`);
    return response.data;
  },

  // 获取个人任务清单
  getPersonalTasks: async (params?: {
    completed?: boolean;
    limit?: number;
    offset?: number;
  }) => {
    const response = await axios.get('/personal-tasks', { params });
    return response.data;
  },

  // 创建个人任务
  createPersonalTask: async (task: Omit<PersonalTask, 'id' | 'createdAt'>) => {
    const response = await axios.post('/personal-tasks', task);
    return response.data;
  },

  // 更新个人任务
  updatePersonalTask: async (id: number, updates: Partial<PersonalTask>) => {
    const response = await axios.patch(`/personal-tasks/${id}`, updates);
    return response.data;
  },

  // 删除个人任务
  deletePersonalTask: async (id: number) => {
    const response = await axios.delete(`/personal-tasks/${id}`);
    return response.data;
  },

  // 检查DDL并生成提醒（系统调用）
  checkDeadlinesAndGenerateReminders: async () => {
    const response = await axios.post('/notifications/check-deadlines');
    return response.data;
  },

  // 获取通知设置
  getNotificationSettings: async () => {
    const response = await axios.get('/notifications/settings');
    return response.data;
  },

  // 更新通知设置
  updateNotificationSettings: async (settings: any) => {
    const response = await axios.patch('/notifications/settings', settings);
>>>>>>> 5468ddbcb29f92919cffedbc7b4859832e875670:qianduan/src/api/notification.ts
    return response.data;
  }
};

export default notificationApi;
